param:
  appid: "wxa220c96305df34c8"
  secret: "52f876d7eff95730a5ea44ec3688eca9"
  grant_type: "authorization_code"
  #获取的登陆码
  js_code: "JSCODE"
  wx_url: "https://api.weixin.qq.com/sns/jscode2session?appid=${param.appid}&secret=${param.secret}&js_code=${param.js_code}&grant_type=${param.grant_type}"
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus?characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  # 图片访问的虚拟前缀
  mvc:
    static-path-pattern: /**
  # 图片的绝对路径
#  resources:
#    static-locations: file:E://checkimage/
  resources:
    static-locations: classpath:/**
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.batis.demobatis.entity